eureka:
  client:
    serviceUrl:
#      defaultZone: http://192.168.1.62:8001/eureka/
      defaultZone: http://localhost:8001/eureka/
server:
  #port: 3532
  port: 8002
spring:
  application:
    name: youfan-zuul
    zuul:
      host:
        socket-timeout-millis: 60000
        connect-timeout-millis: 60000
  http:
    multipart:
      enabled: true   # 启用http上传处理
      max-file-size: 100MB # 设置单个文件的最大长度
      max-request-size: 100MB # 设置最大的请求文件的大小
      file-size-threshold: 1MB  # 当上传文件达到1MB的时候进行磁盘写入
      location: /  # 上传的临时目录
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000


